# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  statusPanelView: allBranchesLog
  filterMode: fuzzy
  nerdFontsVersion: '3'
  showDivergenceFromBaseBranch: 'arrowAndNumber'
  sidePanelWidth: 0.25

git:
  paging:
    pager: 'delta'

confirmOnQuit: true

customCommands:
  - key: 'u'
    context: 'commits'
    description: 'Restore changes from file'
    prompts:
      - type: 'input'
        title: 'Select a file to restore its changes:'
        key: 'fileToRestore'
        suggestions:
          command: 'git diff-tree --no-commit-id --name-only -r {{.SelectedLocalCommit.Sha}}'
      - type: 'confirm'
        title: 'Confirm to restore changes'
        body: 'Are you sure you want to restore the changes of "{{.Form.fileToRestore}}"?.'
    command: 'git restore --source={{.SelectedLocalCommit.Sha}}~1 --worktree -- {{.Form.fileToRestore | quote}}'
    loadingText: 'Restoring file...'
    after:
      checkForConflicts: true
